services:
  git-zipper-bot:
    build: .
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
